name: Generate & Commit package-lock.json (one-shot)

on:
  workflow_dispatch:

permissions:
  contents: write   # permite que el workflow haga push

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # usa GITHUB_TOKEN para el push

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Limpia cualquier lockfile inválido y node_modules
      - name: Regenerate lockfile
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Commit lockfile
        run: |
          if [ -f package-lock.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: add valid package-lock.json (npm@18)" || echo "No changes"
            git push
          else
            echo "package-lock.json not found after npm install"
            exit 1
          fi
