name: "Deploy Now: Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'   # >=18 vale; 22 OK
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build + export estático (desactiva i18n porque NEXT_EXPORT=true)
      - name: Build & Export static
        run: npm run export:static
        env:
          NEXT_EXPORT: "true"
          # Si tu app necesita la URL pública en build:
          # NEXT_PUBLIC_SITE_URL: ${{ inputs.site-url }}

      # Publica /out como artefacto para Deploy Now
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploynow-artifact
          path: out
