# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: out

jobs:
  # Please do not rename this job
  build-project:
    name: build Togthr-template-Next
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node (Next 12)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # SIN cache: 'npm' para no requerir lockfile en este paso

      # Usa el lockfile que subiste (si no existe, usa npm install)
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --production
          fi

      - name: Build & Export static site
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          npm run build
          npm run export

      # Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 89d51bd0-2e9c-41b7-b495-60c58532221c
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Togthr-template-Next/config.yaml
          action: upload
